FinanceSoftTestProject/FinanceSoftTestProject/Models/ChatUser.cs
namespace FinanceSoftTestProject.Models
{
    public class ChatUser
    {
        public int UserId { get; set; }
        public string ConnectionId { get; set; }
        public string Name { get; set; }
    }
}

FinanceSoftTestProject/FinanceSoftTestProject/Models/LoginModel.cs
using System.ComponentModel.DataAnnotations;

namespace FinanceSoftTestProject.Models
{
    public class LoginModel
    {
        [Required]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

FinanceSoftTestProject/FinanceSoftTestProject/Models/LoginResult.cs
using FinanceSoftTestProject.BLL.DTO;

namespace FinanceSoftTestProject.Models
{
    public class LoginResult : ResultModel
    {
        public UserDTO UserData {get; set; }
    }
}

FinanceSoftTestProject/FinanceSoftTestProject/Models/RegisterModel.cs
using System.ComponentModel.DataAnnotations;

namespace FinanceSoftTestProject.Models
{
    public class RegisterModel
    {
        [Required]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }

        [Required]
        public string FirstName { get; set; }

        [Required]
        public string LastName { get; set; }
    }
}

FinanceSoftTestProject/FinanceSoftTestProject/Models/ResultModel.cs
namespace FinanceSoftTestProject.Models
{
    public class ResultModel
    {
        public bool IsSucceed { get; set; }
        public string ErrorMessages { get; set; }
    }
}

FinanceSoftTestProject/FinanceSoftTestProject/Models/SendMessageResult.cs
using FinanceSoftTestProject.BLL.DTO;

namespace FinanceSoftTestProject.Models
{
    public class SendMessageResult : ResultModel
    {
        public MessageDTO MessageDTO {get; set; }
    }
}

FinanceSoftTestProject/FinanceSoftTestProject/Controllers/AccountController.cs
using FinanceSoftTestProject.BLL.DTO;
using FinanceSoftTestProject.BLL.Infrastructure;
using FinanceSoftTestProject.BLL.Interfaces;
using FinanceSoftTestProject.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace FinanceSoftTestProject.Controllers
{
    public class AccountController : Controller
    {
        private IUserService UserService => HttpContext.GetOwinContext().GetUserManager<IUserService>();
        private IAuthenticationManager AuthenticationManager => HttpContext.GetOwinContext().Authentication;

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(LoginModel model)
        {
            await SetInitialDataAsync();
            if (ModelState.IsValid)
            {
                UserDTO userDto = new UserDTO { Email = model.Email, Password = model.Password };
                ClaimsIdentity claim = await UserService.Authenticate(userDto);
                if (claim == null)
                {
                    ModelState.AddModelError("", "Неверный логин или пароль.");
                }
                else
                {
                    if (int.TryParse(claim.GetUserId(), out int userId))
                    {
                        userDto.Id = userId;
                    }

                    SignIn(claim);
                    return Json(new LoginResult { IsSucceed = true, UserData = userDto}, JsonRequestBehavior.AllowGet);
                }
            }

            var errorsList = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage);
            return Json(new LoginResult { IsSucceed = false, ErrorMessages = string.Join("; ", errorsList) }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Logout()
        {
            AuthenticationManager.SignOut();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Register(RegisterModel model)
        {
            await SetInitialDataAsync();
            if (ModelState.IsValid)
            {
                UserDTO userDto = new UserDTO
                {
                    Email = model.Email,
                    Password = model.Password,
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Role = "user"
                };
                OperationDetails operationDetails = await UserService.Create(userDto);
                if (operationDetails.Succedeed)
                {
                    ClaimsIdentity claim = await UserService.Authenticate(userDto);
                    var principal = new ClaimsPrincipal(claim);

                    if (int.TryParse(claim.GetUserId(), out int userId))
                    {
                        userDto.Id = userId;
                    }

                    SignIn(claim);
                    return Json(new LoginResult { IsSucceed = true, UserData = userDto}, JsonRequestBehavior.AllowGet);
                }
                else
                    ModelState.AddModelError(operationDetails.Property, operationDetails.Message);
            }

            var errorsList = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage);
            return Json(new LoginResult { IsSucceed = false, ErrorMessages = string.Join("; ", errorsList)}, JsonRequestBehavior.AllowGet);
        }

        private void SignIn(ClaimsIdentity claim)
        {
            AuthenticationManager.SignOut();
            AuthenticationManager.SignIn(new AuthenticationProperties
            {
                IsPersistent = true
            }, claim);
        }

        private async Task SetInitialDataAsync()
        {
            await UserService.SetInitialData(new UserDTO
            {
                Email = "husketbbx@gmail.ru",
                UserName = "husketbbx@gmail.ru",
                Password = "123123",
                FirstName = "Roman",
                LastName = "Sexov",
                Role = "admin",
            }, new List<string> { "user", "admin" });
        }
    }
}

FinanceSoftTestProject/FinanceSoftTestProject/Controllers/ChatController.cs
using FinanceSoftTestProject.BLL.DTO;
using FinanceSoftTestProject.BLL.Interfaces;
using FinanceSoftTestProject.Models;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinanceSoftTestProject.Controllers
{
    public class ChatController : Controller
    {
        private IChatService ChatService => HttpContext.GetOwinContext().Get<IChatService>();

        // GET: Chat
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        // Отображение сообщений в чате
        public ActionResult ChatMessages(DateTime? dateFrom = null, DateTime? dateTo = null)
        {
            var messages = ChatService.GetMessages(dateFrom, dateTo);
            return PartialView(messages.OrderByDescending(x => x.CreatedDateTime));
        }

        [HttpPost]
        public ActionResult Send(MessageDTO message)
        {
            if(message == null)
            {
                return Json(new SendMessageResult { IsSucceed = false, ErrorMessages = "Message can't be null" }, JsonRequestBehavior.AllowGet);
            }
            var result = ChatService.SendMessage(message);
            return Json(new SendMessageResult { IsSucceed = result, MessageDTO = message }, JsonRequestBehavior.AllowGet);
        }
    }
}

FinanceSoftTestProject/FinanceSoftTestProject/Controllers/HomeController.cs
using System.Web.Mvc;

namespace FinanceSoftTestProject.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
    }
}

FinanceSoftTestProject/FinanceSoftTestProject/Views/Chat/ChatMessages.cshtml
@using FinanceSoftTestProject.BLL.DTO;
@using Microsoft.AspNet.Identity

@{
    var userId = User.Identity.GetUserId();
}

@foreach (MessageDTO message in Model)
{
    <p> @message.CreatedDateTime <b> @message.UserName </b>: </p>
    <p class='chatMessage'> @message.Message</p>
}

FinanceSoftTestProject/FinanceSoftTestProject/Views/Chat/Index.cshtml
@using Microsoft.AspNet.Identity

@{
    var userId = User.Identity.GetUserId();
    var userName = User.Identity.GetUserName();
}
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    <h2>Чат-комната</h2>

    <div class="main" data-userId="@userId" data-userName="@userName" data-isLoadedBefore="false">
        <div id="chatBody">
            <div id="header"></div>
            <div class="grid-container">
                <div id="chatroom">
                </div>
                <div>
                    @using (Ajax.BeginForm("ChatMessages", new AjaxOptions
                    {
                        UpdateTargetId = "chatroom",
                        HttpMethod = "GET"
                    }))
                    {
                        <input type="date" data-bind="value: dateFrom" id="dateFrom" name="dateFrom" />
                        <input type="date" data-bind="value: dateTo" id="dateTo" name="dateTo" />
                        <button data-bind="click: filterDate" class="btn btn-primary">Обновить</button>
                    }
                    <br />
                    <div id="inputForm">
                        <textarea data-bind="textInput: txtMessage" class="form-control" id="TxtMessage" cols="40" rows="12"></textarea>
                        <button data-bind="click: sendMessage" class="btn btn-primary">Отправить</button>
                    </div>
                </div>
            </div>

            <div id="onlineform">
                <h5>Онлайн:</h5>
                <div id=chatusers></div>
            </div>


        </div>
        <input id="@userId" type="hidden" />
        <input id="@userName" type="hidden" />
    </div>
</body>
</html>

FinanceSoftTestProject/FinanceSoftTestProject/Views/Home/About.cshtml
@{
}
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    <h2>Чат-комната</h2>

    <div class="main">
        <div id="loginBlock">
            Введите логин:<br />
            <input id="txtUserName" type="text" />
            <input id="btnLogin" type="button" value="Войти" />
        </div>
        <div id="chatBody">
            <div id="header"></div>
            <div id="inputForm">
                <input type="text" id="message" />
                <input type="button" id="sendmessage" value="Отправить" />
            </div>
            <div id="chatroom"></div>

            <div id="chatusers">
                <p><b>Все пользователи</b></p>
            </div>
        </div>
        <input id="hdId" type="hidden" />
        <input id="username" type="hidden" />
    </div>
</body>
</html>

FinanceSoftTestProject/FinanceSoftTestProject/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

FinanceSoftTestProject/FinanceSoftTestProject/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Let's Chat</h1>
    <p class="lead">is a free web chat built on C#, HTML, CSS and JavaScript.</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Application architecture</h2>
        <p>
            The application is built on a three-tier architecture, using ASP.NET MVC 5 web application template.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

FinanceSoftTestProject/FinanceSoftTestProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Let's chat</title>
   
    <!--Ссылка на билблеотеку JS -->
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/knockout-3.5.1.js"></script>
    <!--Ссылка на библиотеку SignalR -->
    <script src="~/Scripts/jquery.signalR-2.4.3.min.js"></script>
    <!--Ссылка на автоматически сгенерированный скрипт хаба SignalR -->
    <script src="~/signalr/hubs"></script>
    <script src="~/Scripts/util.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Let's Chat", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Chat Room", "Index", "Chat")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - FinanceSoft test App</p>
        </footer>
    </div>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>